FROM alpine:3.18

WORKDIR /app

RUN apk add --no-cache nodejs npm sqlite sqlite-dev

COPY package*.json ./

RUN npm install --omit=dev

COPY init-db.js ./
COPY database.js ./

CMD ["node", "init-db.js"]
